// <auto-generated />
using System;
using KK.Var.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KK.Var.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820105747_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("KK.Var.Models.KKProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BuildProvider")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EnvironmentFileFormat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitHubCloneUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubRepositoryFullName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long?>("GitHubRepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HealthCheckAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HealthCheckCommand")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthCheckHttpUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HealthCheckIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HealthCheckStabilityDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HealthCheckTcpPort")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HealthCheckTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthCheckType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalDirectoryPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("ProjectEnvironmentFilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteDeploymentDirectory")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteExecutableFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteServiceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RemoteServiceName")
                        .IsUnique();

                    b.ToTable("KKProjects", null, t =>
                        {
                            t.HasCheckConstraint("CK_KKProjects_Source", "(SourceType = 1 AND LocalDirectoryPath IS NOT NULL AND GitHubRepositoryId IS NULL AND GitHubRepositoryFullName IS NULL AND GitHubCloneUrl IS NULL) OR (SourceType = 2 AND LocalDirectoryPath IS NULL AND GitHubRepositoryId IS NOT NULL AND GitHubRepositoryFullName IS NOT NULL AND GitHubCloneUrl IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("KK.Var.Models.KKProjectDeployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KKProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KKProjectVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("OperationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteOperationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VariablesSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KKProjectVersionId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("KKProjectId", "StartedAtUtc");

                    b.ToTable("KKProjectDeployments", (string)null);
                });

            modelBuilder.Entity("KK.Var.Models.KKProjectEnvironmentVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KKProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KKProjectId", "Name")
                        .IsUnique();

                    b.HasIndex("KKProjectId", "SortOrder")
                        .IsUnique();

                    b.ToTable("KKProjectEnvironmentVariables", (string)null);
                });

            modelBuilder.Entity("KK.Var.Models.KKProjectVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactRelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ArtifactSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KKProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("KKProjectId", "Tag")
                        .IsUnique();

                    b.ToTable("KKProjectVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_KKProjectVersions_ArtifactSize", "ArtifactSize >= 0");
                        });
                });

            modelBuilder.Entity("KK.Var.Models.KKProjectDeployment", b =>
                {
                    b.HasOne("KK.Var.Models.KKProject", "Project")
                        .WithMany("Deployments")
                        .HasForeignKey("KKProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KK.Var.Models.KKProjectVersion", "Version")
                        .WithMany("Deployments")
                        .HasForeignKey("KKProjectVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("KK.Var.Models.KKProjectEnvironmentVariable", b =>
                {
                    b.HasOne("KK.Var.Models.KKProject", "Project")
                        .WithMany("EnvironmentVariables")
                        .HasForeignKey("KKProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("KK.Var.Models.KKProjectVersion", b =>
                {
                    b.HasOne("KK.Var.Models.KKProject", "Project")
                        .WithMany("Versions")
                        .HasForeignKey("KKProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("KK.Var.Models.KKProject", b =>
                {
                    b.Navigation("Deployments");

                    b.Navigation("EnvironmentVariables");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("KK.Var.Models.KKProjectVersion", b =>
                {
                    b.Navigation("Deployments");
                });
#pragma warning restore 612, 618
        }
    }
}
